const Graph = require('./index')

graph = new Graph("root")

const main = () => {
	graph.addCoordinator({ address: "a" })
	graph.addOrUpdateVertex({ address: "b", parents: ["a"] })
	graph.addOrUpdateVertex({ address: "c", parents: ["a"] })
	graph.addOrUpdateVertex({ address: "d", parents: ["a"] })
	graph.addOrUpdateVertex({ address: "e", parents: ["a"] })
	graph.addOrUpdateVertex({ address: "f", parents: ["b"] })
	graph.addOrUpdateVertex({ address: "g", parents: ["c", "d"] })
	graph.addOrUpdateVertex({ address: "h", parents: ["d", "g"] })
	graph.addOrUpdateVertex({ address: "i", parents: ["e"] })
	graph.addOrUpdateVertex({ address: "j", parents: ["i"] })
	graph.addOrUpdateVertex({ address: "k", parents: ["j", "h"] })
	console.log(graph.adjList)
	console.log(graph.getPath("k", 0))
	console.log(graph.getPath("k", 1))
	graph.addOrUpdateVertex({ address: "k", parents: ["h"] })
	console.log(graph.getPath("k", 0))
	console.log(graph.adjList)
	//graph.updateVertex({ address: "c", parents: ["d"] })
	//console.log(graph.getPath("g", 0))
	//graph.removeVertex("e")
	//console.log(graph.getPath("k", 0))
	//console.log(graph.adjList)
	//graph.removeVertex("d")
	//console.log(graph.getPath("k", 0))
	//console.log(graph.adjList)
	//graph.removeVertex("c")
	//console.log(graph.getPath("k", 0))
	//console.log(graph.adjList)
	//graph.removeVertex("c")
	//console.log(graph.getPath("g", 0))
	//console.log(graph.adjList)
	//graph.removeVertex("d")
	//console.log(graph.adjList)

	//console.log(graph.adjList)
	//graph.addVertex({ address: "b", parents: ["aaaa"] })
	//graph.addVertex({ address: "c", parents: ["aaa"] })
	//graph.addVertex({ address: "d", parents: ["b"] })
	//graph.addVertex({ address: "e", parents: ["b"] })
	//graph.addVertex({ address: "f", parents: ["c"] })
	//graph.addVertex({ address: "g", parents: ["c"] })
	//graph.addVertex({ address: "h", parents: ["c"] })
	//graph.addVertex({ address: "i", parents: ["d"] })
	//graph.addVertex({ address: "j", parents: ["d"] })
	//graph.addVertex({ address: "k", parents: ["d"] })
	//graph.addVertex({ address: "l", parents: ["f"] })
	//console.log(graph.getPath(Buffer.from("aaaa"), 0))
	//console.log(graph.getVisGraph())
	//console.log(graph.getVertex("l"))
	//graph.removeVertex("l")
	//console.log(graph.getPath("f", 0))
	//console.log(graph.getPath("b", 0))
	//console.log(graph.getVertex("l"))
}

main()